---
# defaults file for minecraft
minecraft_server: minecraft
minecraft_version: latest
minecraft_manifest: https://piston-meta.mojang.com/mc/game/version_manifest_v2.json
minecraft_user: "{{ minecraft_server }}"
minecraft_group: "{{ minecraft_server }}"
minecraft_home: /srv/{{ minecraft_server }}
minecraft_max_memory: 1024M
minecraft_initial_memory: 1024M
minecraft_service_name: "{{ minecraft_server }}"
minecraft_supervisor_name: "{{ minecraft_service_name }}"
minecraft_whitelist: []
minecraft_ops: []
minecraft_banned_players: []
minecraft_banned_ips: []
minecraft_console_fifo: /run/{{ minecraft_service_name }}/console
minecraft_console_fifo_mode: '0666'
minecraft_process_control: systemd
minecraft_server_properties: {}
dependencies: ['openjdk-17-jre', 'sudo', 'acl'] # TODO: read java runtime major version from version manifest

minecraft_spigot_url: https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
